---
# tasks file for tcpdump
   - name: prep tracing out directory
     file: path={{ r_tcpd_out_dir }} state=directory mode=0700

   - name: tracing on all Ifaces (non_promisc)
     shell: timeout {{ duration }} tcpdump -i any -w {{ r_tcpd_out_dir }}{{ inventory_hostname }} {{ expr }} 
     register: res 
     changed_when: "res.rc  == 124"
     failed_when: "res.rc != 124 and res.rc != 0"

